import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:skill_arc/providers/language_provider.dart';

class AppStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'vi': {
      // General buttons
      'back': 'QUAY LẠI',
      'cancel': 'HỦY',
      'ok': 'ĐỒNG Ý',
      'skip': 'BỎ QUA',
      'save': 'LƯU THAY ĐỔI',
      'loading': 'Đang tải...',
      
      // Chat bot
      'botTitle': 'Trợ lý SkillArc',
      'botStatus': 'AI Assistant • Online',
      'botThinking': 'Trợ lý đang suy nghĩ...',
      'inputHint': 'Nhập câu hỏi của bạn...',
      'botGreeting': 'Xin chào! Tôi là **Trợ lý SkillArc**. Tôi có thể giúp gì cho lộ trình học tập IT của bạn hôm nay? 🚀',
      'quickPrompt1': 'Tư vấn lộ trình học IT',
      'quickPrompt2': 'Giải thích thử thách',
      'quickPrompt3': 'Gợi ý kỹ năng cần học',
      
      // Login & Register
      'login': 'ĐĂNG NHẬP',
      'register': 'ĐĂNG KÝ NGAY',
      'registerTitle': 'ĐĂNG KÝ TÀI KHOẢN',
      'username': 'Tên đăng nhập',
      'password': 'Mật khẩu',
      'confirmPassword': 'Xác nhận mật khẩu',
      'fullName': 'Họ tên',
      'noAccount': 'Chưa có tài khoản? Đăng ký ngay',
      'confirmPasswordMismatch': 'Mật khẩu xác nhận không khớp.',
      'loginFailed': 'Đăng nhập thất bại. Vui lòng kiểm tra lại thông tin.',
      'loginSuccess': 'Đăng nhập thành công!',
      'registerSuccess': 'Đăng ký tài khoản thành công!',
      'registerFailed': 'Đăng ký thất bại. Vui lòng thử lại.',
      
      // Profile & Edit Profile
      'editProfile': 'CHỈNH SỬA HỒ SƠ',
      'phone': 'Số điện thoại',
      'enterEmail': 'Nhập địa chỉ email',
      'enterPhone': 'Nhập số điện thoại của bạn',
      'enterFullName': 'Nhập họ tên của bạn',
      'fullNameRequired': 'Vui lòng nhập họ tên',
      'emailRequired': 'Vui lòng nhập email',
      'bio': 'Tiểu sử / Giới thiệu bản thân',
      'bioHint': 'Ví dụ: Lập trình viên Flutter đam mê công nghệ...',
      'updateProfileSuccess': 'Cập nhật thông tin cá nhân thành công!',
      'saveLocalSuccess': 'Đã lưu cục bộ hồ sơ!',
      'personalInfo': 'Thông tin cá nhân',
      'studyProgress': 'TIẾN ĐỘ HỌC TẬP',
      'learnedSkills': 'Kỹ năng đã học',
      'studyHours': 'Thời gian học',
      'dailyGoal': 'Mục tiêu hàng ngày',
      'accountSettings': 'CÀI ĐẶT TÀI KHOẢN',
      'logout': 'Đăng xuất',
      'appVersion': 'Phiên bản 1.0.0',
      'hoursUnit': 'Giờ',
      'notSetName': 'Chưa đặt tên',
      'notSetEmail': 'Chưa có email',

      // Goal Settings
      'goalTitle': 'MỤC TIÊU HỌC TẬP',
      'goalDesc': 'Thiết lập mục tiêu hàng ngày giúp bạn duy trì kỷ luật và tiến xa hơn trên lộ trình nghề nghiệp.',
      'hoursPerDay': 'Số giờ học mỗi ngày',
      'reminderTime': 'Thời gian nhắc nhở',
      'reminderChange': 'Thay đổi',
      'saveGoal': 'LƯU MỤC TIÊU',
      'saveGoalSuccess': 'Lưu mục tiêu học tập thành công!',
      'testNotification': 'Gửi thử thông báo tức thì',
      'notificationOk': 'Hệ thống thông báo của bạn hoạt động bình thường!',
      'notificationError': 'Lỗi kiểm tra thông báo',
      'batteryOptimizeTitle': 'Khắc phục lỗi không hiện thông báo',
      'batteryOptimizeDesc': 'Một số dòng điện thoại (Xiaomi, Oppo, Vivo, Huawei) tự động chặn thông báo chạy ngầm. Hãy cấp quyền dưới đây để đảm bảo ứng dụng gửi nhắc nhở học tập ổn định:',
      'autoStart': 'Tự khởi chạy',
      'alarmPermission': 'Báo thức chính xác',
      'disableBatteryOptimization': 'Bỏ chặn pin',

      // Explore & Articles
      'searchHint': 'Tìm kiếm bài viết, mẹo học tập...',
      'noResults': 'Không tìm thấy nội dung phù hợp',
      'searchResult': 'KẾT QUẢ TÌM KIẾM',
      'clearSearch': 'Xóa tìm kiếm',
      'categories': 'DANH MỤC',
      'forYou': 'DÀNH CHO BẠN',
      'all': 'Tất cả',
      'themePrefix': 'CHỦ ĐỀ: ',
      'articlesCount': 'bài viết',
      'readTimeSuffix': 'đọc',
      'commentsTitle': 'BÌNH LUẬN',
      'commentHint': 'Nhập bình luận của bạn...',
      'shareArticle': 'CHIA SẺ BÀI VIẾT',
      'copyLink': 'Sao chép link',
      'message': 'Tin nhắn',
      'email': 'Email',
      'copiedLinkToast': 'Đã sao chép liên kết vào bộ nhớ tạm',
      'shareMessageToast': 'Đã mở hòm thư chia sẻ qua Tin nhắn',
      'shareEmailToast': 'Đã mở hòm thư chia sẻ qua Email',
      'like': 'Thích',
      'comment': 'Bình luận',
      'isLikedToast': 'Đã thích bài viết',
      'isUnlikedToast': 'Đã bỏ thích',
      'isBookmarkedToast': 'Đã lưu bài viết vào mục yêu thích',
      'isUnbookmarkedToast': 'Đã bỏ lưu bài viết',
      'loadingVideo': '▶️ Đang tải video hướng dẫn khóa học...',
      'likePrompt': 'Bạn thấy bài viết này hữu ích?',
      'likedStatus': 'Vừa thích',
      'daysAgo': '2 ngày trước',

      // Challenges
      'challengeTitle': 'Chi tiết thử thách',
      'challengeLocked': 'Thử thách này hiện đang bị khóa.',
      'dailyChallenge': 'THỬ THÁCH HÀNG NGÀY',
      'lockedChallenge': 'THỬ THÁCH ĐANG KHÓA',
      'specialEvent': 'SỰ KIỆN ĐẶC BIỆT',
      'hackathon': 'HACKATHON CUỐI TUẦN',
      'noChallenges': 'Không có thử thách nào.',
      'submitCoding': 'Nộp bài giải (Link Github hoặc nội dung bài làm):',
      'submitHint': 'Nhập link repository hoặc code tại đây...',
      'aiFeedback': 'AI NHẬN XÉT CHI TIẾT',
      'submitButton': 'NỘP BÀI',
      'retryButton': 'THỬ LẠI',
      'finishClose': 'HOÀN THÀNH (ĐÓNG)',
      'correctAnswerToast': 'Chúc mừng! Bạn đã trả lời đúng thử thách.',
      'incorrectAnswerToast': 'Đáp án chưa chính xác, hãy xem gợi ý và thử lại nhé!',
      'selectOptionToast': 'Vui lòng chọn một đáp án!',
      'submitRequiredToast': 'Vui lòng nhập link bài làm hoặc nội dung giải thuật!',
      'submitFailedToast': 'Nộp bài thất bại, vui lòng thử lại!',
      'joinChallengeSuccess': 'Đã tham gia thử thách thành công!',

      // Skill Tree
      'skillDetailTitle': 'Chi tiết kỹ năng',
      'prerequisiteRequired': 'Yêu cầu hoàn thành kỹ năng trước',
      'markCompleted': 'ĐÁNH DẤU HOÀN THÀNH',
      'markUncompleted': 'HỦY HOÀN THÀNH',
      'skillsLocked': 'Nội dung này đang bị khóa.',
      'skillsMastered': 'Bạn đã làm chủ kỹ năng này!',
      'skillsStart': 'Hãy bắt đầu học kỹ năng này ngay.',
      'skillsTapDetail': 'Nhấn để xem chi tiết lộ trình học',
      
      // Home Screen
      'journeyOverview': 'TỔNG QUAN HÀNH TRÌNH',
      'forecastTitle': 'DỰ BÁO LỘ TRÌNH AI',
      'forecastDesc': 'Dựa trên mục tiêu {hours}h/ngày và {skills} kỹ năng còn lại.',
      'skillsRemaining': 'Còn lại',
      'daysToFinish': 'Ngày về đích',
      'daysUnit': 'ngày',
      'activeSkills': 'KỸ NĂNG ĐANG CHINH PHỤC',
      'completedAll': 'Bạn đã hoàn thành mọi mục tiêu hiện tại!',
      'continueLearning': 'TIẾP TỤC HỌC',
      'todayReminder': 'NHẮC NHỞ HÔM NAY',
      'realProject': 'DỰ ÁN THỰC TẾ CỦA BẠN',
      'usedTechnology': 'CÔNG NGHỆ SỬ DỤNG',
      'projectDescTitle': 'MÔ TẢ CHI TIẾT & THÀNH TỰU',
      'learnNow': 'HỌC NGAY',
      'welcomeBack': 'Chào mừng trở lại,',
      'skillsLearned': 'Đã học',
      'ratio': 'Tỷ lệ',
      'reviewTitle': 'NỘI DUNG ÔN TẬP GỢI Ý',
      
      // Missing keys added
      'titleResetChallenge': 'Đặt lại thử thách',
      'descResetChallenge': 'Bạn có chắc chắn muốn đặt lại tất cả tiến độ thử thách không? Hành động này không thể hoàn tác.',
      'btnReset': 'ĐẶT LẠI',
      'navHome': 'Trang chủ',
      'navRoadmap': 'Lộ trình',
      'navExplore': 'Khám phá',
      'navChallenge': 'Thử thách',
      'navProfile': 'Hồ sơ',
      'commentAuthorYou': 'Bạn',
      'commentAuthorUser': 'Học viên',
      'specialEvents': 'SỰ KIỆN ĐẶC BIỆT',
      'lockedChallenges': 'THỬ THÁCH ĐÃ KHÓA',
      'weekendHackathon': 'Hackathon Cuối Tuần',
      'hackathonDesc': 'Tham gia giải quyết bài toán thực tế cùng hàng ngàn lập trình viên khác.',
      'joinNow': 'THAM GIA NGAY',
      'catProgramming': 'Lập trình',
      'catMobile': 'Di động',
      'catNetworking': 'Mạng máy tính',
      'catDatabase': 'Cơ sở dữ liệu',
      'categoriesTitle': 'DANH MỤC',
      'searchResults': 'KẾT QUẢ TÌM KIẾM',
      'recommendedForYou': 'DÀNH CHO BẠN',
      'topicTitle': 'CHỦ ĐỀ',
      'noArticlesFound': 'Không tìm thấy bài viết nào',
      'startLearningNow': 'Bắt đầu học ngay',
      'startChallengesToBuildChart': 'Hãy làm thử thách để vẽ biểu đồ',
      'specialistOop': 'Chuyên gia Hướng đối tượng',
      'specialistMobile': 'Chuyên gia Di động',
      'specialistBackend': 'Chuyên gia Backend',
      'specialistNetwork': 'Chuyên gia Mạng',
      'wellRoundedDev': 'Nhà phát triển Toàn diện',
      'defaultUsername': 'Học viên',
      'competencyChart': 'BIỂU ĐỒ NĂNG LỰC',
      'trending': 'Xu hướng',
      'Lộ trình Phát triển SkillArc & Hệ thống': 'Lộ trình Phát triển SkillArc & Hệ thống',
      'progressPrefix': 'Tiến độ: {percentage}% - {status}',
      'Hoàn thành xuất sắc!': 'Hoàn thành xuất sắc!',
      'Tiếp tục cố gắng': 'Tiếp tục cố gắng',
      'timeLabel': 'Thời gian: {time}',
      'OOP Core': 'Lập trình OOP',
      'Mobile Dev': 'Lập trình Mobile',
      'Backend': 'Phát triển Backend',
      'Network': 'Hạ tầng mạng',
      'Ôn tập kỹ năng Flutter Cơ bản': 'Ôn tập kỹ năng Flutter Cơ bản',
      'Làm bài tập Java Spring Boot': 'Làm bài tập Java Spring Boot',
      'notifTitle': 'Đã đến giờ học rồi!',
      'notifBody': 'Mục tiêu hôm nay của bạn là học {hours} tiếng. Cố gắng lên nhé!',
      'errorPrefix': 'Lỗi:',
      'prerequisiteError': 'Bạn phải hoàn thành kỹ năng tiền đề trước!',
    },
    'en': {
      // General buttons
      'back': 'BACK',
      'cancel': 'CANCEL',
      'ok': 'OK',
      'skip': 'SKIP',
      'save': 'SAVE CHANGES',
      'loading': 'Loading...',
      
      // Chat bot
      'botTitle': 'SkillArc Assistant',
      'botStatus': 'AI Assistant • Online',
      'botThinking': 'Assistant is thinking...',
      'inputHint': 'Type your question...',
      'botGreeting': 'Hello! I am **SkillArc Assistant**. How can I help with your IT learning path today? 🚀',
      'quickPrompt1': 'Advise IT study path',
      'quickPrompt2': 'Explain challenge',
      'quickPrompt3': 'Suggest skills to learn',
      
      // Login & Register
      'login': 'LOG IN',
      'register': 'REGISTER NOW',
      'registerTitle': 'CREATE AN ACCOUNT',
      'username': 'Username',
      'password': 'Password',
      'confirmPassword': 'Confirm Password',
      'fullName': 'Full Name',
      'noAccount': 'No account? Register now',
      'confirmPasswordMismatch': 'Passwords do not match.',
      'loginFailed': 'Login failed. Please check your credentials.',
      'loginSuccess': 'Logged in successfully!',
      'registerSuccess': 'Account created successfully!',
      'registerFailed': 'Registration failed. Please try again.',
      
      // Profile & Edit Profile
      'editProfile': 'EDIT PROFILE',
      'phone': 'Phone Number',
      'enterEmail': 'Enter email address',
      'enterPhone': 'Enter your phone number',
      'enterFullName': 'Enter your full name',
      'fullNameRequired': 'Full name is required',
      'emailRequired': 'Email is required',
      'bio': 'Bio / Introduction',
      'bioHint': 'E.g., Passionate Flutter developer...',
      'updateProfileSuccess': 'Profile updated successfully!',
      'saveLocalSuccess': 'Profile saved locally!',
      'personalInfo': 'Personal Information',
      'studyProgress': 'STUDY PROGRESS',
      'learnedSkills': 'Skills learned',
      'studyHours': 'Study hours',
      'dailyGoal': 'Daily goal',
      'accountSettings': 'ACCOUNT SETTINGS',
      'logout': 'Log Out',
      'appVersion': 'Version 1.0.0',
      'hoursUnit': 'Hours',
      'notSetName': 'Name not set',
      'notSetEmail': 'No email',

      // Goal Settings
      'goalTitle': 'LEARNING GOAL',
      'goalDesc': 'Setting a daily goal helps you maintain discipline and progress further in your career.',
      'hoursPerDay': 'Study hours per day',
      'reminderTime': 'Reminder Time',
      'reminderChange': 'Change',
      'saveGoal': 'SAVE GOAL',
      'saveGoalSuccess': 'Learning goal saved successfully!',
      'testNotification': 'Send instant test notification',
      'notificationOk': 'Your notification system is working normally!',
      'notificationError': 'Notification test error',
      'batteryOptimizeTitle': 'Fix notification display issues',
      'batteryOptimizeDesc': 'Some phones (Xiaomi, Oppo, Vivo, Huawei) block background alerts. Grant permissions below for stable learning reminders:',
      'autoStart': 'Auto-start',
      'alarmPermission': 'Exact Alarm',
      'disableBatteryOptimization': 'Ignore battery optimization',

      // Explore & Articles
      'searchHint': 'Search articles, study tips...',
      'noResults': 'No matching content found',
      'searchResult': 'SEARCH RESULTS',
      'clearSearch': 'Clear Search',
      'categories': 'CATEGORIES',
      'forYou': 'FOR YOU',
      'all': 'All',
      'themePrefix': 'TOPIC: ',
      'articlesCount': 'articles',
      'readTimeSuffix': 'read',
      'commentsTitle': 'COMMENTS',
      'commentHint': 'Type your comment...',
      'shareArticle': 'SHARE ARTICLE',
      'copyLink': 'Copy Link',
      'message': 'Message',
      'email': 'Email',
      'copiedLinkToast': 'Link copied to clipboard',
      'shareMessageToast': 'Opened sharing via Messages',
      'shareEmailToast': 'Opened sharing via Email',
      'like': 'Like',
      'comment': 'Comment',
      'isLikedToast': 'Article liked',
      'isUnlikedToast': 'Like removed',
      'isBookmarkedToast': 'Article bookmarked',
      'isUnbookmarkedToast': 'Bookmark removed',
      'loadingVideo': '▶️ Loading tutorial video...',
      'likePrompt': 'Did you find this article helpful?',
      'likedStatus': 'Just liked',
      'daysAgo': '2 days ago',

      // Challenges
      'challengeTitle': 'Challenge Details',
      'challengeLocked': 'This challenge is currently locked.',
      'dailyChallenge': 'DAILY CHALLENGE',
      'lockedChallenge': 'LOCKED CHALLENGE',
      'specialEvent': 'SPECIAL EVENT',
      'hackathon': 'WEEKEND HACKATHON',
      'noChallenges': 'No challenges available.',
      'submitCoding': 'Submit Solution (Github link or source code):',
      'submitHint': 'Enter repository link or code here...',
      'aiFeedback': 'AI FEEDBACK DETAILS',
      'submitButton': 'SUBMIT',
      'retryButton': 'RETRY',
      'finishClose': 'FINISH (CLOSE)',
      'correctAnswerToast': 'Congratulations! You answered correctly.',
      'incorrectAnswerToast': 'Incorrect answer, check hints and try again!',
      'selectOptionToast': 'Please select an option!',
      'submitRequiredToast': 'Please enter solution URL or content!',
      'submitFailedToast': 'Submission failed, please try again!',
      'joinChallengeSuccess': 'Successfully joined the challenge!',

      // Skill Tree
      'skillDetailTitle': 'Skill Details',
      'prerequisiteRequired': 'Prerequisite skill required',
      'markCompleted': 'MARK COMPLETED',
      'markUncompleted': 'MARK UNCOMPLETED',
      'skillsLocked': 'This content is currently locked.',
      'skillsMastered': 'You have mastered this skill!',
      'skillsStart': 'Start learning this skill now.',
      'skillsTapDetail': 'Tap to view detailed path',
      
      // Home Screen
      'journeyOverview': 'JOURNEY OVERVIEW',
      'forecastTitle': 'AI PATH FORECAST',
      'forecastDesc': 'Based on target {hours}h/day and {skills} remaining skills.',
      'skillsRemaining': 'Remaining',
      'daysToFinish': 'Target Day',
      'daysUnit': 'days',
      'activeSkills': 'ACTIVE SKILLS',
      'completedAll': 'You have achieved all current goals!',
      'continueLearning': 'CONTINUE LEARNING',
      'todayReminder': 'TODAY REMINDERS',
      'realProject': 'YOUR PRACTICAL PROJECT',
      'usedTechnology': 'TECHNOLOGY USED',
      'projectDescTitle': 'PROJECT DESCRIPTION & ACHIEVEMENTS',
      'learnNow': 'LEARN NOW',
      'welcomeBack': 'Welcome back,',
      'skillsLearned': 'Learned',
      'ratio': 'Ratio',
      'reviewTitle': 'SUGGESTED REVIEW CONTENT',
      
      // Missing keys added
      'titleResetChallenge': 'Reset Challenges',
      'descResetChallenge': 'Are you sure you want to reset all challenge progress? This action cannot be undone.',
      'btnReset': 'RESET',
      'navHome': 'Home',
      'navRoadmap': 'Roadmap',
      'navExplore': 'Explore',
      'navChallenge': 'Challenge',
      'navProfile': 'Profile',
      'commentAuthorYou': 'You',
      'commentAuthorUser': 'Learner',
      'specialEvents': 'SPECIAL EVENTS',
      'lockedChallenges': 'LOCKED CHALLENGES',
      'weekendHackathon': 'Weekend Hackathon',
      'hackathonDesc': 'Join in solving real-world problems with thousands of other developers.',
      'joinNow': 'JOIN NOW',
      'catProgramming': 'Programming',
      'catMobile': 'Mobile',
      'catNetworking': 'Networking',
      'catDatabase': 'Database',
      'categoriesTitle': 'CATEGORIES',
      'searchResults': 'SEARCH RESULTS',
      'recommendedForYou': 'RECOMMENDED FOR YOU',
      'topicTitle': 'TOPIC',
      'noArticlesFound': 'No articles found',
      'startLearningNow': 'Start learning now',
      'startChallengesToBuildChart': 'Complete challenges to build chart',
      'specialistOop': 'OOP Specialist',
      'specialistMobile': 'Mobile Specialist',
      'specialistBackend': 'Backend Specialist',
      'specialistNetwork': 'Network Specialist',
      'wellRoundedDev': 'Well-rounded Developer',
      'defaultUsername': 'Learner',
      'competencyChart': 'COMPETENCY CHART',
      'trending': 'Trending',
      
      // Dynamic Data Translations
      // Skills
      'Nền tảng Công nghệ & Lập trình Cơ bản': 'IT Fundamentals & Basic Programming',
      'Nhóm kỹ năng cơ sở ngành CNTT': 'IT core foundation skills group',
      'Lập trình hướng đối tượng (OOP) & Cấu trúc dữ liệu': 'Object-Oriented Programming (OOP) & Data Structures',
      'Nền tảng tư duy logic, thuật toán, xử lý cấu trúc dữ liệu và giải thuật cơ bản.': 'Logic, algorithm foundation, data structures, and basic algorithms processing.',
      'Ngôn ngữ lập trình Java & C#': 'Java & C# Programming Languages',
      'Làm chủ cú pháp, xây dựng ứng dụng console và nền tảng hướng đối tượng đa hình.': 'Master syntax, build console apps, and object-oriented polymorphism.',
      'Phát triển Ứng dụng Di động (Mobile Development)': 'Mobile Development',
      'Xây dựng giao diện di động đa nền tảng': 'Build multi-platform mobile interfaces',
      'Flutter Framework & Dart': 'Flutter Framework & Dart',
      'Xây dựng giao diện UI/UX đa nền tảng mượt mà, sử dụng Widget và quản lý trạng thái với Provider.': 'Build smooth multi-platform UI/UX, using Widgets and managing state with Provider.',
      'Lưu trữ cục bộ & Tích hợp API (Hive & RESTful API)': 'Local Storage & API Integration (Hive & RESTful API)',
      'Quản lý dữ liệu NoSQL nhẹ với Hive, kết nối RESTful API đồng bộ dữ liệu với Backend.': 'Manage lightweight NoSQL data with Hive, connect RESTful API to sync data with Backend.',
      'Phát triển Hệ thống Backend': 'Backend System Development',
      'Thiết kế hệ thống máy chủ và lưu trữ dữ liệu': 'Server system and data storage design',
      'Spring Boot & RESTful Web Services': 'Spring Boot & RESTful Web Services',
      'Xây dựng hệ thống backend vững chắc, viết RestController, xử lý logic nghiệp vụ và bảo mật.': 'Build solid backend system, write RestControllers, business logic and security.',
      'Quản trị Cơ sở dữ liệu MySQL & MongoDB': 'MySQL & MongoDB Database Administration',
      'Thiết kế cơ sở dữ liệu quan hệ, viết câu lệnh truy vấn tối ưu và ánh xạ Hibernate/JPA.': 'Design relational databases, write optimized queries, and Hibernate/JPA mapping.',
      'Hạ tầng Mạng, Ảo hóa & Triển khai': 'Network Infrastructure, Virtualization & Deployment',
      'Quy hoạch mạng doanh nghiệp và vận hành ảo hóa': 'Enterprise network planning and virtualization operations',
      'Hạ tầng mạng doanh nghiệp (Cisco Packet Tracer / GNS3)': 'Enterprise Network Infrastructure (Cisco Packet Tracer / GNS3)',
      'Cấu hình định tuyến OSPF, EIGRP, VLAN, quy hoạch IP Subnetting và bảo mật VPN Site-to-Site.': 'Configure OSPF dynamic routing, EIGRP, VLANs, IP Subnetting, and Site-to-Site VPN security.',
      'Ảo hóa hệ thống & Ubuntu Deployment (VMware / Linux)': 'System Virtualization & Ubuntu Deployment (VMware / Linux)',
      'Cài đặt và cấu hình Ubuntu 24.04 LTS trên VMware Workstation Pro, quản lý dòng lệnh Linux.': 'Install and configure Ubuntu 24.04 LTS on VMware Workstation Pro, manage Linux commands.',

      // Challenges
      'Tối ưu hóa truy vấn SQL và Indexing bảng dữ liệu lớn': 'Optimizing SQL Queries and Indexing Large Tables',
      'Làm thế nào để tăng tốc truy vấn SELECT trên bảng có 10 triệu dòng? | Đánh chỉ mục (Index) trên các cột thường xuyên tìm kiếm': 'How to speed up SELECT queries on a table with 10 million rows? | Indexing frequently searched columns',
      'Xây dựng Provider quản lý trạng thái giỏ hàng / tiến độ trong Flutter': 'Building a Provider to Manage Cart State / Progress in Flutter',
      'Viết class CartProvider kế thừa ChangeNotifier để quản lý danh sách sản phẩm giỏ hàng.': 'Write a CartProvider class inheriting from ChangeNotifier to manage product list in the cart.',
      'Cấu hình bảo mật JWT Authentication trong Spring Boot RESTful API': 'Configuring JWT Authentication Security in Spring Boot RESTful API',
      'Viết logic cấu hình SecurityFilterChain để bảo mật các endpoint bằng JWT.': 'Write configurations for SecurityFilterChain to secure endpoints with JWT.',
      'Thiết kế và chia Subnet mạng IPv4 cho hệ thống 3 chi nhánh doanh nghiệp': 'Designing and Subnetting IPv4 Network for a 3-Branch Enterprise System',
      'Chia dải IP 192.168.1.0/24 thành các subnet để cấp đủ IP cho 3 chi nhánh có số lượng host khác nhau.': 'Subnet 192.168.1.0/24 to provide enough IP addresses for 3 branches with different host requirements.',

      // Challenge options
      'Đánh chỉ mục (Index) trên các cột thường xuyên tìm kiếm': 'Indexing frequently searched columns',
      'Giải pháp không sử dụng đánh chỉ mục (Index)': 'Solutions without using Index',
      'Xóa bớt dữ liệu thừa trên bảng lớn': 'Deleting redundant data on large tables',
      'Sử dụng mệnh đề WHERE phức tạp không tối ưu': 'Using unoptimized complex WHERE clauses',

      // Difficulty / Categories
      'DỄ': 'EASY',
      'TRUNG BÌNH': 'MEDIUM',
      'KHÓ': 'HARD',

      // Articles
      'Lập trình Hướng đối tượng OOP chuyên sâu với Java & C#': 'Advanced Object-Oriented Programming (OOP) with Java & C#',
      'Lập trình hướng đối tượng (OOP) là nền tảng cốt lõi của hầu hết các ngôn ngữ lập trình hiện đại như Java và C#.\n\n1. Các nguyên lý cơ bản của OOP:\n• Đóng gói (Encapsulation): Che giấu thông tin chi tiết và bảo vệ dữ liệu bên trong đối tượng thông qua private fields và public getters/setters.\n• Kế thừa (Inheritance): Tái sử dụng mã nguồn bằng cách cho phép lớp con kế thừa thuộc tính và phương thức từ lớp cha.\n• Đa hình (Polymorphism): Cho phép một phương thức hành xử khác nhau dựa trên đối tượng gọi nó. Ví dụ: nạp chồng (overloading) và ghi đè (overriding).\n• Trừu tượng (Abstraction): Tập trung vào giao diện bên ngoài của đối tượng thay vì chi tiết triển khai nội bộ thông qua Interface và Abstract Class.\n\n2. Điểm khác biệt giữa Java và C#:\nMặc dù cả hai đều là ngôn ngữ OOP mạnh mẽ, Java quản lý bộ nhớ hoàn toàn bằng Garbage Collector tự động và chạy trên JVM, trong khi C# chạy trên CLR (.NET Framework) và hỗ trợ các tính năng hiện đại như Properties trực tiếp, LINQ, và con trỏ không an toàn (unsafe code) khi cần thiết.': 'Object-Oriented Programming (OOP) is the core foundation of most modern programming languages like Java and C#.\n\n1. Basic Principles of OOP:\n• Encapsulation: Hiding internal details and protecting data through private fields and public getters/setters.\n• Inheritance: Reusing code by allowing a subclass to inherit fields and methods from a superclass.\n• Polymorphism: Allowing a method to behave differently based on the calling object. E.g., overloading and overriding.\n• Abstraction: Focusing on the external interface of an object rather than its internal implementation details using Interfaces and Abstract Classes.\n\n2. Key Differences Between Java and C#:\nAlthough both are powerful OOP languages, Java manages memory entirely with an automatic Garbage Collector running on the JVM, while C# runs on the CLR (.NET Framework) and supports modern features like direct Properties, LINQ, and unsafe pointers when needed.',

      'Tối ưu hiệu năng ứng dụng Flutter với RepaintBoundary': 'Optimizing Flutter App Performance with RepaintBoundary',
      'Trong Flutter, việc tối ưu hóa render (hiệu năng giao diện) là cực kỳ quan trọng để đạt 60fps hoặc 120fps mượt mà.\n\n1. RepaintBoundary là gì?\nMỗi khi một Widget được vẽ lại (repaint), Flutter sẽ đi qua toàn bộ Widget cây để repaint. RepaintBoundary tạo ra một layer vẽ riêng biệt, cô lập việc vẽ lại của một Widget con khỏi phần còn lại của màn hình.\n\n2. Khi nào nên sử dụng?\n• Sử dụng cho các Widget chuyển động liên tục (như hoạt ảnh xoay tròn, hiệu ứng nhấp nháy, Canvas vẽ tự do).\n• Sử dụng cho các phần giao diện tĩnh cực kỳ phức tạp nhưng nằm cạnh một phần giao diện động.\n\n3. Lưu ý:\nKhông lạm dụng RepaintBoundary cho mọi Widget vì việc tạo ra quá nhiều Layer vẽ riêng biệt sẽ ngốn dung lượng bộ nhớ GPU.': 'In Flutter, optimizing render (UI performance) is crucial to achieve a smooth 60fps or 120fps experience.\n\n1. What is RepaintBoundary?\nEvery time a Widget is repainted, Flutter traverses the entire Widget tree. RepaintBoundary creates a separate drawing layer, isolating the repaint of a child Widget from the rest of the screen.\n\n2. When to Use?\n• Use for continuously animating Widgets (such as spinning loaders, blinking effects, custom canvas drawings).\n• Use for highly complex static UI sections located next to a dynamic UI section.\n\n3. Notes:\nDo not over-use RepaintBoundary for every Widget, as creating too many separate layers will increase GPU memory consumption.',

      'Cấu hình định tuyến động OSPF trên giả lập Cisco GNS3': 'Configuring Dynamic OSPF Routing on Cisco GNS3 Simulator',
      'Giao thức OSPF (Open Shortest Path First) là giao thức định tuyến động dạng Link-State được sử dụng rộng rãi nhất trong mạng doanh nghiệp hiện nay.\n\n1. Các bước triển khai cơ bản trên Router Cisco:\n• Bước 1: Kích hoạt tiến trình OSPF bằng lệnh `router ospf <process-id>`.\n• Bước 2: Thiết lập router ID định danh duy nhất.\n• Bước 3: Quảng bá mạng trực tiếp thông qua lệnh `network <ip-address> <wildcard-mask> area <area-id>`.\n\n2. Tại sao lại chia Area?\nOSPF chia mạng thành các Area (vùng) để giảm dung lượng bảng cơ sở dữ liệu trạng thái đường truyền (LSDB) trên mỗi router. Vùng trung tâm bắt buộc phải là Area 0 (Backbone Area).': 'OSPF (Open Shortest Path First) is the most widely used dynamic Link-State routing protocol in enterprise networks today.\n\n1. Basic Deployment Steps on Cisco Routers:\n• Step 1: Enable the OSPF process using the `router ospf <process-id>` command.\n• Step 2: Establish a unique router ID identifier.\n• Step 3: Advertise directly connected networks using the `network <ip-address> <wildcard-mask> area <area-id>` command.\n\n2. Why Divide Areas?\nOSPF divides the network into Areas to reduce the link-state database (LSDB) size on each router. The central zone must be Area 0 (Backbone Area).',

      'Tích hợp Hive database & RESTful API trong ứng dụng Flutter': 'Integrating Hive Database & RESTful API in Flutter Apps',
      'Để xây dựng một ứng dụng Mobile chất lượng, chiến lệ kết hợp Offline-First bằng cách lưu trữ cục bộ (Hive) và đồng bộ qua API (RESTful API) là lựa chọn tối ưu.\n\n1. Tại sao dùng Hive?\nHive là cơ sở dữ liệu key-value được viết hoàn toàn bằng Dart, tốc độ cực nhanh và hoạt động mượt mà trên thiết bị di động mà không cần file binary SQLite cồng kềnh.\n\n2. Cách đồng bộ dữ liệu:\n• Bước 1: Gọi API qua HTTP để nhận dữ liệu JSON mới nhất từ Backend (Spring Boot/Node.js).\n• Bước 2: Lưu trực tiếp dữ liệu đó vào Hive box.\n• Bước 3: UI sẽ lắng nghe thay đổi của Hive box để cập nhật giao diện lập tức (ngay cả khi mất kết nối mạng, dữ liệu cũ vẫn hiển thị bình thường).': 'To build a high-quality mobile app, combining Offline-First local storage (Hive) and API synchronization (RESTful API) is the optimal choice.\n\n1. Why Use Hive?\nHive is a key-value database written entirely in Dart. It is incredibly fast and runs smoothly on mobile devices without heavy SQLite binaries.\n\n2. Data Synchronization Steps:\n• Step 1: Call API via HTTP to receive the latest JSON data from the Backend (Spring Boot/Node.js).\n• Step 2: Save the data directly into a Hive box.\n• Step 3: UI listens to changes in the Hive box to update the interface instantly (even when disconnected, old data is shown normally).',

      'Bảo mật hệ điều hành Ubuntu Server cho doanh nghiệp': 'Securing Ubuntu Server for Enterprises',
      'Hệ điều hành Ubuntu Server là lựa chọn hàng đầu của doanh nghiệp, tuy nhiên cấu hình mặc định chưa đủ an toàn để chống lại các cuộc tấn công mạng.\n\nCác bước tăng cường bảo mật (Hardening):\n1. Cập nhật hệ thống: Chạy lệnh `sudo apt update && sudo apt upgrade` thường xuyên.\n2. Bảo mật SSH: Thay đổi cổng SSH mặc định 22 sang một cổng khác. Vô hiệu hóa đăng nhập bằng tài khoản root trực tiếp (`PermitRootLogin no`) và chuyển sang xác thực bằng SSH Key thay cho mật khẩu.\n3. Kích hoạt Firewall: Sử dụng UFW (Uncomplicated Firewall) để chỉ cho phép các cổng dịch vụ cần thiết (như 80, 443, cổng SSH mới) đi qua.': 'Ubuntu Server is the top choice for enterprises; however, the default configuration is not secure enough to resist cyber attacks.\n\nHardening Steps:\n1. Update System: Run `sudo apt update && sudo apt upgrade` regularly.\n2. Secure SSH: Change the default SSH port 22 to a different port. Disable direct root login (`PermitRootLogin no`) and switch to SSH Key authentication instead of passwords.\n3. Enable Firewall: Use UFW (Uncomplicated Firewall) to allow only necessary service ports (such as 80, 443, and the new SSH port).',

      // Projects
      'Tối ưu Lộ trình Học (SkillArc)': 'Learning Path Optimization (SkillArc)',
      '🎓 Đồ án cơ sở chuyên ngành CNTT trường Đại học Nguyễn Tất Thành. Ứng dụng tối ưu hóa lộ trình học tập của sinh viên dựa trên sơ đồ hình cây năng lực và các thử thách lập trình/trắc nghiệm liên tục.': '🎓 IT core foundation project at Nguyen Tat Thanh University. An app to optimize student learning paths based on a competency skill tree and continuous programming/quiz challenges.',
      'Ứng dụng Quản lý Tài chính': 'Financial Management App',
      '🏆 Đạt giải Khuyến khích – Cuộc thi Trí tuệ Nhân tạo do Khoa CNTT tổ chức. Ứng dụng giúp theo dõi chi tiêu cá nhân thông minh và tích hợp cơ sở dữ liệu SQLite đồng bộ đám mây Firebase.': '🏆 Consolation Prize winner – AI Competition organized by the IT Department. Smart personal expense tracker integrated with SQLite database and Firebase cloud sync.',
      'Hệ thống Mạng Doanh nghiệp': 'Enterprise Network System',
      '⚙️ Cấu hình định tuyến động OSPF, chia subnet mạng IPv4 bảo mật cho hệ thống 3 chi nhánh doanh nghiệp lớn, tích hợp VPN bảo mật và triển khai máy chủ ảo hóa Ubuntu phục vụ nội bộ.': '⚙️ Configure dynamic OSPF routing, subnet secure IPv4 network for a 3-branch enterprise system, integrate secure VPN, and deploy virtualization Ubuntu servers for internal use.',
      
      // Additional home screen strings
      'Lộ trình Phát triển SkillArc & Hệ thống': 'SkillArc & System Development Path',
      'progressPrefix': 'Progress: {percentage}% - {status}',
      'Hoàn thành xuất sắc!': 'Excellent completion!',
      'Tiếp tục cố gắng': 'Keep trying',
      'timeLabel': 'Time: {time}',
      'OOP Core': 'OOP Core',
      'Mobile Dev': 'Mobile Dev',
      'Backend': 'Backend',
      'Network': 'Network',
      'Ôn tập kỹ năng Flutter Cơ bản': 'Review Basic Flutter skills',
      'Làm bài tập Java Spring Boot': 'Practice Java Spring Boot exercises',
      'notifTitle': 'Time to study!',
      'notifBody': 'Your goal today is to study {hours} hours. Keep it up!',
      'errorPrefix': 'Error:',
      'prerequisiteError': 'You must complete the prerequisite skill first!',
    }
  };

  static String of(BuildContext context, String key, {Map<String, String>? placeholders}) {
    final locale = Provider.of<LanguageProvider>(context).currentLocale;
    String value = _localizedValues[locale]?[key] ?? key;
    if (placeholders != null) {
      placeholders.forEach((k, v) {
        value = value.replaceAll('{$k}', v);
      });
    }
    return value;
  }

  static String get(String key, String locale, {Map<String, String>? placeholders}) {
    String value = _localizedValues[locale]?[key] ?? key;
    if (placeholders != null) {
      placeholders.forEach((k, v) {
        value = value.replaceAll('{$k}', v);
      });
    }
    return value;
  }
}
